name: CI

on:
  push:
    branches: [ main, master, '**' ]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Use Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Show Nix versions
        run: |
          nix --version
          nix flake --version || true

      - name: Nix fmt check
        run: |
          nix fmt -- --check

      - name: Nix flake check
        run: |
          nix flake check --all-systems

      - name: Install deadnix and statix
        run: |
          nix profile install nixpkgs#deadnix nixpkgs#statix

      - name: deadnix
        run: |
          deadnix --fail .

      - name: statix
        run: |
          statix check .


